const quoteId = window.location.pathname.split("/").pop();
const statusBox = document.querySelector("#review-status");
let current;
const showStatus = (message, error=false) => { statusBox.className = `status ${error ? "error" : "success"}`; statusBox.textContent = message; };
const request = async (path, options={}) => { const response = await fetch(path, options); const body = await response.json(); if(!response.ok) throw new Error(body.error || "Request failed"); return body; };
const display = (value) => value === null || value === undefined || value === "" ? "Not provided" : value;
function render(draft){ current=draft; const i=draft.intake; const fields={"Customer":i.full_name,"Email":i.email,"Phone":i.phone,"Job type":i.job_type,"Location":i.service_location,"Urgency":i.urgency,"Property / site":i.job_details.property_type,"Preferred timing":i.job_details.preferred_timing,"Job details":i.job_details.scope_summary,"Notes":i.notes}; const dl=document.querySelector("#raw-input"); dl.replaceChildren(); Object.entries(fields).forEach(([k,v])=>{const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=k;dd.textContent=display(v);dl.append(dt,dd)}); const uploads=document.querySelector("#uploads");uploads.replaceChildren();(draft.uploads.length?draft.uploads:[null]).forEach(u=>{const li=document.createElement("li");li.textContent=u?`${u.category}: ${u.content_type}, ${u.size_bytes} bytes`:"No uploads provided";uploads.append(li)}); if(!draft.original_ai_recommendation)return; const a=draft.original_ai_recommendation,h=draft.human_version;document.querySelector("#analysis-empty").hidden=true;document.querySelector("#analysis").hidden=false;document.querySelector("#summary").value=h?.summary||a.summary;document.querySelector("#price-range").textContent=`AI recommended range: $${a.price_min} – $${a.price_max}`;document.querySelector("#final-price").value=h?.final_price||"";document.querySelector("#assumptions").value=(h?.assumptions||a.assumptions).join("\n");document.querySelector("#confidence").textContent=`Confidence: ${a.confidence}%`; const items=document.querySelector("#line-items");items.replaceChildren();(h?.line_items||a.line_items).forEach(x=>{const row=document.createElement("div");row.className="line-row";row.innerHTML='<input class="line-description"><input class="line-amount" type="number" min="0" step="0.01">';row.children[0].value=x.description;row.children[1].value=x.amount;items.append(row)}); for(const [id,values,format] of [["risks",draft.risk_flags,x=>x],["evidence",a.evidence,x=>`${x.input_field}: ${x.fact}`]]){const list=document.querySelector(`#${id}`);list.replaceChildren();values.forEach(v=>{const li=document.createElement("li");li.textContent=format(v);list.append(li)})}}
async function load(){try{render(await request(`/securequote/api/intakes/${quoteId}`))}catch(e){showStatus(e.message,true)}}load();
document.querySelector("#analyze").onclick=async()=>{try{showStatus("Analysis requested. Waiting for validated provider output…");render(await request(`/securequote/api/intakes/${quoteId}/analyze`,{method:"POST"}));showStatus("Analysis validated. Human approval is still required.")}catch(e){showStatus(e.message,true)}};
const humanVersion=()=>({summary:document.querySelector("#summary").value,line_items:[...document.querySelectorAll(".line-row")].map(r=>({description:r.querySelector(".line-description").value,amount:r.querySelector(".line-amount").value})),final_price:document.querySelector("#final-price").value,assumptions:document.querySelector("#assumptions").value.split("\n").map(x=>x.trim()).filter(Boolean)});
document.querySelector("#save-edit").onclick=async()=>{try{render(await request(`/securequote/api/intakes/${quoteId}/edit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(humanVersion())}));showStatus("Human edit saved. Original AI recommendation preserved.")}catch(e){showStatus(e.message,true)}};
document.querySelector("#approve").onclick=async()=>{try{const data=new FormData();data.set("final_price",document.querySelector("#final-price").value);render(await request(`/securequote/api/intakes/${quoteId}/approve`,{method:"POST",body:data}));showStatus("Approved internally. Nothing was sent to the customer.")}catch(e){showStatus(e.message,true)}};
for(const [id,path,msg] of [["reject","reject","Quote rejected."],["more-info","request-more-info","More information required. No message was sent."]])document.querySelector(`#${id}`).onclick=async()=>{try{render(await request(`/securequote/api/intakes/${quoteId}/${path}`,{method:"POST"}));showStatus(msg)}catch(e){showStatus(e.message,true)}};
